name = "Exdir"
uuid = "22fff31a-bb86-4dc7-a268-e891319ab808"
authors = ["Eric Berquist <eric.berquist@gmail.com> and contributors"]
version = "0.1.0"

[deps]
NPZ = "15e1cf62-19b3-5cfa-8e77-841668bca605"
YAML = "ddb6d928-2868-570f-bddf-ab3f9cf99eb6"

[compat]
julia = "1"

[extras]
EllipsisNotation = "da5c29d0-fa7d-589e-88eb-ea29b0a81949"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
StructArrays = "09ab397b-f2b6-538f-b94a-2f83cf4a842a"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["EllipsisNotation", "HDF5", "StructArrays", "Test"]
